# Generated by Django 5.1.7 on 2025-04-05 12:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("questions", "0003_usernote"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="difficulty",
            field=models.CharField(
                choices=[
                    ("UNMARKED", "Unmarked"),
                    ("EASY", "Easy"),
                    ("MEDIUM", "Medium"),
                    ("HARD", "Hard"),
                ],
                default="MEDIUM",
                max_length=10,
            ),
        ),
    ]
