# Generated by Django 5.1.7 on 2025-03-19 12:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_alter_customuser_is_accepted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="is_accepted",
            field=models.BooleanField(default=False),
        ),
    ]
