# Generated by Django 5.1.7 on 2025-04-05 12:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_alter_customuser_is_accepted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="rank",
            field=models.CharField(
                blank=True, default="Chulbul Pandey", max_length=50, null=True
            ),
        ),
    ]
