# Generated by Django 5.1.7 on 2025-07-07 05:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_alter_customuser_rank"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="preferred_language",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
